### ISSUE TITLE
Starting up the BYFN network using CouchDB

### ISSUE THREAD

**Issue by vorlkets** [PacktPublishing/Hyperledger-Cookbook#1]
Hi, while sudo ./bydn.sh up -c mychannel -s couchdb as on page 32 of the book, I got the following error:

peer0.org1 failed to join the channel, Retry after 3 seconds
+ peer channel join -b mychannel.block
+ res=1
+ set +x
Error: error getting endorser client for channel: endorser client failed to connect to peer0.org1.example.com:7051: failed to create new connection: context deadline exceeded
!!!!!!!!!!!!!!! After 10 attempts, peer0.org1 has failed to join channel 'mychannel'  !!!!!!!!!!!!!!!!
========= ERROR !!! FAILED to execute End-2-End Scenario ===========

What's going on here?

**Comment by brian8151** [comment]
Hi vorlkets:
The error indicates that something related to the network connection error.  You can update retry attempt time to a larger number i.e e. 50 or update 3 seconds to 10 sec. But it typically makes sure the network connection is fine. You can try it another time to see if the issue is gone. 
Thanks
Brian
